In [43]:
import glob
traj_files = glob.glob('traj_data/talented-steel-butterfly*.csv')

In [44]:
traj_files

['traj_data/talented-steel-butterfly_17.csv',
 'traj_data/talented-steel-butterfly_03.csv',
 'traj_data/talented-steel-butterfly_18.csv',
 'traj_data/talented-steel-butterfly_10.csv',
 'traj_data/talented-steel-butterfly_12.csv',
 'traj_data/talented-steel-butterfly_16.csv',
 'traj_data/talented-steel-butterfly_06.csv',
 'traj_data/talented-steel-butterfly_00.csv',
 'traj_data/talented-steel-butterfly_13.csv',
 'traj_data/talented-steel-butterfly_02.csv',
 'traj_data/talented-steel-butterfly_04.csv',
 'traj_data/talented-steel-butterfly_15.csv',
 'traj_data/talented-steel-butterfly_01.csv',
 'traj_data/talented-steel-butterfly_11.csv',
 'traj_data/talented-steel-butterfly_08.csv',
 'traj_data/talented-steel-butterfly_05.csv',
 'traj_data/talented-steel-butterfly_19.csv',
 'traj_data/talented-steel-butterfly_07.csv',
 'traj_data/talented-steel-butterfly_14.csv',
 'traj_data/talented-steel-butterfly_09.csv']

In [34]:
import pandas as pd
import numpy as np
res = 0.01
for traj_file in traj_files:
    # with open(traj_files[0], 'r') as f:
    row = pd.read_csv(traj_file)
    errors = []
    for i in range(200):
        dX = np.array([row.iloc[i+1]['dX'], row.iloc[i+1]['dY'], row.iloc[i+1]['dX1'], row.iloc[i+1]['dY1']])
        X1 = np.array([row.iloc[i]['X'], row.iloc[i]['Y'], row.iloc[i]['X1'], row.iloc[i]['Y1']])
        X2 = np.array([row.iloc[i+1]['X'], row.iloc[i+1]['Y'], row.iloc[i+1]['X1'], row.iloc[i+1]['Y1']])
        errors.append(list(X2-X1-dX*res))
    errors = np.array(errors)
    print(np.mean(errors, axis=0), np.std(errors, axis=0))
#     print(np.mean(errors), np.std(errors))

[ 4.641610e-05 -9.906125e-05  3.286825e-05 -9.105395e-05] [0.00145925 0.00140612 0.00098514 0.00168499]
[-4.601135e-05  6.547800e-06  1.106275e-05  3.332840e-05] [0.00087569 0.00158476 0.00159784 0.00079399]
[-4.963855e-05  7.960980e-05 -7.353600e-05  1.119907e-04] [0.00129453 0.0011577  0.00149256 0.00157091]
[ 6.764500e-05 -2.542015e-05  1.330610e-04 -4.699100e-06] [0.00099581 0.00117333 0.00171198 0.00128975]
[-9.052635e-05 -4.749950e-05 -8.927695e-05 -3.591435e-05] [0.00144255 0.00157677 0.00188282 0.0014085 ]
[ 2.98431e-05 -9.26796e-05  4.90436e-05 -4.17726e-05] [0.00039724 0.00105955 0.00023872 0.00103381]
[-8.13675e-06 -9.22109e-05 -3.78047e-05 -5.61802e-05] [0.00099766 0.00113463 0.00077223 0.00118507]
[ 5.728465e-05  3.639635e-05  3.094545e-05 -5.420100e-06] [0.0004372  0.00111371 0.00054107 0.00118602]
[1.085115e-05 4.593935e-05 3.566490e-05 6.194820e-05] [0.00088399 0.00121661 0.00094324 0.00088255]
[ 6.695575e-05 -5.362520e-05  7.267685e-05 -8.004705e-05] [0.00074164 0.0011

In [45]:
import pandas as pd
import numpy as np
res = 0.01
for traj_file in traj_files:
    # with open(traj_files[0], 'r') as f:
    row = pd.read_csv(traj_file)
    errors = []
    for i in range(200):
        dX = np.array([row.iloc[i+1]['dX'], row.iloc[i+1]['dY'], row.iloc[i+1]['dX1'], row.iloc[i+1]['dY1']])
        X1 = np.array([row.iloc[i]['X'], row.iloc[i]['Y'], row.iloc[i]['X1'], row.iloc[i]['Y1']])
        X2 = np.array([row.iloc[i+1]['X'], row.iloc[i+1]['Y'], row.iloc[i+1]['X1'], row.iloc[i+1]['Y1']])
        errors.append(list(X2-X1-dX*res))
    errors = np.array(errors)
    print(np.mean(errors, axis=0), np.std(errors, axis=0))
#     print(np.mean(errors), np.std(errors))

[-3.829920e-05  5.210290e-05  3.635450e-06  3.172435e-05] [0.00070309 0.00131861 0.00061805 0.00111918]
[8.124270e-05 2.040170e-05 3.728845e-05 2.670860e-05] [0.00044622 0.00050338 0.00029022 0.00040787]
[ 7.4096600e-05 -1.0777945e-04  1.2886400e-05 -2.5421700e-05] [0.0013246  0.00044715 0.00106928 0.00075384]
[-3.582305e-05 -1.899060e-05 -5.493095e-05  2.491280e-05] [0.00114708 0.00022986 0.00045548 0.00061815]
[ 2.383320e-05  1.248450e-06  2.759990e-05 -1.250675e-05] [0.0005824  0.00116658 0.00030042 0.00094738]
[-3.680535e-05 -1.627448e-04  3.042570e-05 -1.420679e-04] [0.00110457 0.000621   0.00090994 0.00081506]
[-5.599005e-05  7.576355e-05 -2.209050e-06  1.339805e-05] [0.00134198 0.00073263 0.00096529 0.00097599]
[-1.590915e-05 -3.639290e-05 -3.561245e-05 -9.987400e-06] [0.00037873 0.00111991 0.00039615 0.00104565]
[-1.80762e-05  1.51805e-05  1.90565e-06 -1.65823e-05] [0.00067966 0.00112435 0.00076912 0.00074488]
[-3.625455e-05  3.062175e-05 -1.731100e-06  4.694805e-05] [0.0009780

In [46]:
row

ID                    System     t         X         Y  \
0    1567203498038683880!  talented-steel-butterfly  0.00  1.382094  0.434754   
1    1567203498038683880!  talented-steel-butterfly  0.01  1.376282  0.423385   
2    1567203498038683880!  talented-steel-butterfly  0.02  1.360590  0.393068   
3    1567203498038683880!  talented-steel-butterfly  0.03  1.337912  0.350125   
4    1567203498038683880!  talented-steel-butterfly  0.04  1.310267  0.298967   
..                    ...                       ...   ...       ...       ...   
196  1567203498038683880!  talented-steel-butterfly  1.96 -0.339664 -2.206954   
197  1567203498038683880!  talented-steel-butterfly  1.97 -0.339867 -2.207242   
198  1567203498038683880!  talented-steel-butterfly  1.98 -0.340062 -2.207520   
199  1567203498038683880!  talented-steel-butterfly  1.99 -0.340250 -2.207788   
200  1567203498038683880!  talented-steel-butterfly  2.00 -0.340430 -2.208046   

           X1        Y1        X2        Y2        dX        dY       dX1  \
0    0.382679  0.468966  0.929788 -0.368096  0.000000  0.000000  0.000000   
1    0.377023  0.461877  0.927965 -0.372666 -1.163186 -2.270602 -1.130300   
2    0.361832  0.442895  0.922996 -0.384810 -1.977012 -3.788649 -1.906617   
3    0.340075  0.415850  0.915700 -0.401864 -2.556194 -4.789416 -2.439988   
4    0.313839  0.383419  0.906622 -0.421944 -2.966428 -5.426875 -2.799020   
..        ...       ...       ...       ...       ...       ...       ...   
196 -1.151517 -1.623091 -0.494622 -0.869108 -0.020049 -0.028451 -0.058512   
197 -1.152086 -1.623889 -0.499014 -0.866594 -0.019323 -0.027477 -0.055472   
198 -1.152626 -1.624647 -0.503391 -0.864059 -0.018622 -0.026535 -0.052439   
199 -1.153135 -1.625363 -0.507754 -0.861502 -0.017947 -0.025626 -0.049414   
200 -1.153614 -1.626038 -0.512103 -0.858924 -0.017297 -0.024750 -0.046398   

          dY1       dX2       dY2           U1          U2          U3  
0    0.000000  0.000000  0.000000  1020.630418 -609.701761 -221.901344  
1   -1.416882 -0.366518 -0.912654   676.827808 -414.153606 -140.408827  
2   -2.377622 -0.630584 -1.512503   440.451960 -279.785274  -84.260024  
3   -3.025183 -0.830366 -1.892098   274.180776 -184.017625  -45.379318  
4   -3.451659 -0.985009 -2.116466   156.044692 -114.440130  -18.546873  
..        ...       ...       ...          ...         ...         ...  
196 -0.081932 -0.439924  0.250367     9.554513   22.060972  -32.152951  
197 -0.077808 -0.438489  0.252496     9.730128   22.001880  -32.265327  
198 -0.073677 -0.437035  0.254612     9.905158   21.942277  -32.376654  
199 -0.069545 -0.435579  0.256723    10.079569   21.882206  -32.487021  
200 -0.065410 -0.434122  0.258830          NaN         NaN         NaN  

[201 rows x 18 columns]